name: open PR when card moved

on:
  repository_dispatch:
    types: [PR_OPEN]

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install @octokit/rest

      - name: Create Pull Request
        run: |
          node -e "
          (async () => {
            const { Octokit } = await import('@octokit/rest');
            const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });
            try {
              console.log(github)
              const { data: pullRequest } = await octokit.pulls.create({
                owner: '${{ github.repository_owner }}',
                repo: '${{ github.repository }}',
                title: 'PR Title',
                body: 'PR Body',
                head: '${{ github.event.client_payload.issue_key }}',
                base: 'develop'
              });
              console.log('Pull request created:', pullRequest.html_url);
            } catch (error) {
              console.error('Error creating pull request:', error);
              process.exit(1);
            }
          })();
          "
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
